### ISSUE TITLE
Encountered an attributeError

### ISSUE THREAD

**Issue by skr1998** [gaganmanku96/Finding-missing-person-using-AI#1]
![Screenshot (6)](https://user-images.githubusercontent.com/31947849/78910521-b8af2c80-7aa2-11ea-95ac-a2c8fad8557a.png)
How to solve this please?

**Comment by gaganmanku96** [comment]
@skr1998 It is giving error because you'll have to upload images through a script that is already there.
Ideally, the image was supposed to be uploaded through the Android app but I misplaced the app this is why I created a script. I might have forgotten to put a check in case no image is present.
