### ISSUE TITLE
Target Refused to Connect

### ISSUE THREAD

**Issue by akshayud4641** [gaganmanku96/Finding-missing-person-using-AI#12]
HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: //login?username=admin&password=admin (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020B19BE3DC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by gaganmanku96** [comment]
@akshayud4641 Did you run docker-compose up before it?

**Comment by akshayud4641** [comment]
Actually I never used docker.....can you please send me something to understand and how to run docker -compose??

**Comment by gaganmanku96** [comment]
Just install Docker. If you are using Windows, it will automatically install docker-compose, on Ubuntu you'll have to install it separately.

https://docs.docker.com/compose/

**Comment by akshayud4641** [comment]
Thanks a lot
