### ISSUE TITLE
I want to contact you regarding ur project plz contact me 8756226198 or give me your contact number plz

### ISSUE THREAD

**Issue by sa11u** [gaganmanku96/Finding-missing-person-using-AI#14]

**Comment by gaganmanku96** [comment]
@sa11u You can reach out to me on LinkedIn or Email.

**Comment by sa11u** [comment]
Whats ir mail id

**Comment by gaganmanku96** [comment]
gaganmanku96@gmail.com

**Comment by sa11u** [comment]
I have mailed you plz check and response plz

**Comment by gaganmanku96** [comment]
@sa11u I haven't got any mail. Can you verify the email address?

**Comment by sa11u** [comment]
Salman.111.sln@gmail.com

**Comment by gaganmanku96** [comment]
Nope. I haven't got any mail from you.

**Comment by sa11u** [comment]
Give me ur contact number or any source i can tslk to u

**Comment by sa11u** [comment]
Again mailed u plz check
