### ISSUE TITLE
result error

### ISSUE THREAD

**Issue by sushruth5454** [gaganmanku96/Finding-missing-person-using-AI#16]
when we match a case instead of showing only matched case it is displaying total database

**Comment by gaganmanku96** [comment]
Can you describe what you did? Like if you added 2 photos from the main app from 1 from the mobile app.

**Comment by sushruth5454** [comment]
yes we have added 4 to5 photos from main app and 1 photo from mobile app.when we match it is showing all photos that were added from main app. 
I think there is a problem in face matching closest distance

**Comment by gaganmanku96** [comment]
It is working fine for me. The 4-5 images that you added, they are different, right?

**Comment by sushruth5454** [comment]
yes. i have uploaded different images

**Comment by ESCANOORLSOP** [comment]
when i try to save it's showing "something went wrong while saving"

**Comment by gaganmanku96** [comment]
Does it print any error message on the console? Can you check once?
