### ISSUE TITLE
incompatibility issues

### ISSUE THREAD

**Issue by samhithanuthi** [gaganmanku96/Finding-missing-person-using-AI#17]
while installing libraries (pip install -r requirements.txt) I got these errors
ERROR: thinc 8.0.1 has requirement pydantic<1.8.0,>=1.7.1, but you'll have pydantic 1.8.2 which is incompatible.
ERROR: spacy 3.0.1 has requirement pydantic<1.8.0,>=1.7.1, but you'll have pydantic 1.8.2 which is incompatible.
ERROR: en-core-web-sm 2.3.1 has requirement spacy<2.4.0,>=2.3.0, but you'll have spacy 3.0.1 which is incompatible.
how to resolve these errors?

**Comment by gaganmanku96** [comment]
Create a fresh python environment. Spacy is not needed and not even installed.
The incompatibility is because you already have it.

**Comment by samhithanuthi** [comment]
You mean I have to re install the python environment?
