### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Madhurireddy1** [gaganmanku96/Finding-missing-person-using-AI#18]
hey um is the project fully completed? I wanna try and implement it.

**Comment by gaganmanku96** [comment]
I've made few changes recently which I've not pushed yet. It would be better if you could implement it tomorrow.
I'll try to push the changes by tonight.

**Comment by Madhurireddy1** [comment]
yes, thank you and can I ping you for doubts? That would be really helpful

**Comment by gaganmanku96** [comment]
Sure

**Comment by Allanetizen** [comment]
I ran this application successfully , the interface is awesome but I was not able to upload the data for a new case. It keeps saying "something went wrong while saving"

**Comment by eig0r** [comment]
i think problem in image source i faced this case too in some images , you can check the server log may you found something like that ( | psycopg2.errors.StringDataRightTruncation: value too long for type character varying(200000) )

**Comment by gaganmanku96** [comment]
@eig0r In Database directory, edit the table_queries file and change value in user_submission, change image varchar(200000) to bigger number like image varchar(800000). It will solve your problem.

Just remember, the table might have been already created, in that case, nothing would happen. So, you'll have to delete that table first.

**Comment by gaganmanku96** [comment]
I would also suggest changing the value in submitted_cases_table.

**Comment by ESCANOORLSOP** [comment]
When i try to upload an image it's showing Couldn't find face in the image
