### ISSUE TITLE
keyError:'status'

### ISSUE THREAD

**Issue by vinz-1203** [gaganmanku96/Finding-missing-person-using-AI#19]
when i try running it and enter username and password it gives this error

Traceback (most recent call last):
  File "login_window.py", line 67, in login
    if login_status['status'] == True:
KeyError: 'status'

**Comment by gaganmanku96** [comment]
@vinz-1203 what credentials (username and password) did you use for login?

**Comment by vinz-1203** [comment]
Admin admin

**Comment by gaganmanku96** [comment]
try admin admin

**Comment by vinz-1203** [comment]
Yeah I tried this too but same error

**Comment by vinz-1203** [comment]
Ok I will try and get back to you thank you so much for your help
