### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by meghugarg** [gaganmanku96/Finding-missing-person-using-AI#2]
I have an error when I am installing lib firebase_admin using pip install firebase_admin.
![IMG_20200428_143548](https://user-images.githubusercontent.com/36644618/80469069-b03d6980-895d-11ea-9d2f-c4699301fdbe.jpg)

**Comment by gaganmanku96** [comment]
@meghugarg which version of python are you using?

**Comment by meghugarg** [comment]
Python 3.8 but I am installing this libraries in anaconda prompt.

**Comment by gaganmanku96** [comment]
@meghugarg I checked the firebase_admin pip and it is only compatible till python 3.7.

Here's what you can do.
1. Create new conda environment using
conda create -n env_name python=3.6
2. Try installing in that env and let me know if the problem still occurs.
