### ISSUE TITLE
Issue on Version .

### ISSUE THREAD

**Issue by IeeeXpert** [gaganmanku96/Finding-missing-person-using-AI#20]
<a href="http://www.ieeexpert.com/ieee-vlsi-projects-2016-2017-vlsi-project-titles/">IEEE VLSI Projects</a>

<a href="http://www.ieeexpert.com/ieee-python-projects-2021-2022-machine_learning-project-titles/
">IEEE Python Projects</a>

**Comment by gaganmanku96** [comment]
@IeeeXpert sorry couldn't understand your problem.
