### ISSUE TITLE
database Issue

### ISSUE THREAD

**Issue by Rahulsatpute07** [gaganmanku96/Finding-missing-person-using-AI#23]
- database is not running  issue how to solve this issue

**Comment by gaganmanku96** [comment]
Please find the Youtube videos link to run the database.

[YT Videos](https://www.youtube.com/channel/UC7ln87o0Gt8OkkHIqEmeDQw/videos)

**Comment by anuj1530** [comment]
Good morning
Sir can you send finding missing person using AI project file on my mail.

**Comment by Rahulsatpute07** [comment]
Thank you very much for your help in this project. Please give me the
documents or the black book help me immediately.
