### ISSUE TITLE
One file missing

### ISSUE THREAD

**Issue by t698** [gaganmanku96/Finding-missing-person-using-AI#25]
db_api.py file is not attached in github source code

**Comment by shubhankar105** [comment]
Yes can we please get access to that file

**Comment by DanBrown47** [comment]
@Chetan-4798 Project is dead imo

**Comment by Chetan-4798** [comment]
> @Chetan-4798 Project is dead imo

Any idea where do i get this project

**Comment by gaganmanku96** [comment]
> db_api.py file is not attached in github source code

File name has changed. It is now main.py
