### ISSUE TITLE
This application failed to start because no Qt platform plugin could be initialized.

### ISSUE THREAD

**Issue by greysou1** [gaganmanku96/Finding-missing-person-using-AI#3]
![Screenshot 2020-05-12 at 2 06 54 PM](https://user-images.githubusercontent.com/29304096/81661510-d7b22d00-9459-11ea-9550-09224362aae0.jpg)
Can you please help me with this?

**Comment by gaganmanku96** [comment]
Which version of opencv-python are you using? @greysou1

**Comment by greysou1** [comment]
opencv-python==4.2.0.34

I also tried installing opencv-python-headless==4.2.0.34 like [this comment](https://github.com/ageitgey/face_recognition/issues/1041#issuecomment-582401795) suggests

**Comment by gaganmanku96** [comment]
try this version of opencv-python 4.1.2.30.
4.2 is said to have many issues.

**Comment by greysou1** [comment]
Thank you! That worked! The workflow is a little confusing, I added a new case and hit refresh but when I click "match", the program exits throwing this error. 
![Screenshot 2020-05-12 at 4 00 21 PM](https://user-images.githubusercontent.com/29304096/81673714-b0fbf280-9469-11ea-8415-b783071be023.jpg)
Thanks again.

**Comment by gaganmanku96** [comment]
No, match face isn't going to open the camera. Opening the camera and matching the face would mean this is a face matching project which isn't the case.
I suggest you reading the README file.
In short you'll need to run upload_user_image.py file and then click on match face button.
